"""Renders results/summary_tables.md from the three raw result files."""
import json, os

R = os.path.join(os.path.dirname(__file__), '..', 'results')
OUT = os.path.join(R, 'summary_tables.md')


def load(name):
    with open(os.path.join(R, name)) as fh:
        return json.load(fh)


def main():
    raw, ex, pw = load('raw_results.json'), load('extras_results.json'), load('power_results.json')
    L = []
    w = L.append

    w('# Dorabella — summary tables (2026-09-04)\n')
    w('Generated by `src/report.py` from `raw_results.json`, `extras_results.json` '
      'and `power_results.json`. All figures are reproducible from `src/` with the '
      'seeds recorded in those files.\n')

    v = raw['language_model_validation']
    w('## 0. Reference-language validation\n')
    w('The English reference model is generated (no corpus egress was available); it is '
      'accepted only because it reproduces published English statistics:\n')
    w('| quantity | model | reference |')
    w('|---|---|---|')
    w('| index of coincidence | %.5f | 0.0667 |' % v['ic'])
    w('| RMS letter-frequency error | %.3f pp | — |\n' % v['rms_error_pct_points'])

    w('## 1. Per-reading statistics\n')
    w('| id | reading | kind | n | distinct | IC | H (bits) | doubles | rep. bigrams | longest repeat |')
    w('|---|---|---|---|---|---|---|---|---|---|')
    for r in raw['readings']:
        w('| %d | %s | %s | %d | %d | %.4f | %.3f | %d | %d | %d |' % (
            r['id'], r['label'], r['kind'], r['n'], r['distinct'], r['ic'],
            r['entropy_bits'], r['doubles'], r['repeated_bigram_types'], r['longest_repeat']))
    w('')

    w('## 2. Relabelling-invariant agreement (fraction of the 3,741 position pairs '
      'on which two readings agree about whether the two positions carry the same symbol)\n')
    w('| reading A | reading B | agreement |')
    w('|---|---|---|')
    for p in raw['pairwise_agreement']:
        w('| %s | %s | %.4f |' % (p['a'], p['b'], p['agree']))
    w('')

    w('## 3. Descriptive statistics against an English null (%d draws of 87 spaceless '
      'English characters)\n' % raw['english_null_87']['n_draws'])
    w('| statistic | English mean | English sd | English 95%% interval |')
    w('|---|---|---|---|')
    for k, s in raw['english_null_87'].items():
        if k == 'n_draws':
            continue
        w('| %s | %.4f | %.4f | [%.4f, %.4f] |' % (k, s['mean'], s['sd'], s['p2.5'], s['p97.5']))
    w('')
    w('Percentile of the English null lying below each observed value '
      '(≈0 or ≈1 would indicate an un-English reading):\n')
    w('| reading | IC | distinct | doubles | rep. bigrams | longest repeat |')
    w('|---|---|---|---|---|---|')
    for r in raw['reading_vs_english_null']:
        w('| %s | %.4f (p=%.3f) | %d (p=%.3f) | %d (p=%.3f) | %d (p=%.3f) | %d (p=%.3f) |' % (
            r['label'], r['ic']['value'], r['ic']['pct_of_english_below'],
            r['distinct']['value'], r['distinct']['pct_of_english_below'],
            r['doubles']['value'], r['doubles']['pct_of_english_below'],
            r['repeated_bigram_types']['value'], r['repeated_bigram_types']['pct_of_english_below'],
            r['longest_repeat']['value'], r['longest_repeat']['pct_of_english_below']))
    w('')

    w('## 4. Periodic index of coincidence (test for a short polyalphabetic period)\n')
    labs = list(ex['periodic_ic']['1']['readings'].keys())
    w('| period | English null (mean ± sd) | ' + ' | '.join(labs) + ' |')
    w('|---' * (len(labs) + 2) + '|')
    for p in range(1, 11):
        e = ex['periodic_ic'][str(p)]
        row = '| %d | %.4f ± %.4f | ' % (p, e['english_null']['mean'], e['english_null']['sd'])
        row += ' | '.join('%.4f' % e['readings'][l]['ic'] for l in labs) + ' |'
        w(row)
    w('')

    w('## 5. Transcription instability\n')
    w('Independent transcriptions compared: %s\n' % ', '.join(ex['independent_transcriptions']))
    w('**%d of 87 positions** are unstable — i.e. the transcriptions disagree about '
      'whether that position carries the same symbol as at least one other position.\n'
      % ex['n_unstable_positions'])
    w('| position | line | conflicting partner positions |')
    w('|---|---|---|')
    for u in ex['unstable_positions']:
        w('| %d | %d | %d |' % (u['position'], u['line'] + 1, u['conflicting_partners']))
    w('')

    w('## 6. Solver calibration (mean log10 quadgram probability per quadgram; '
      'higher is more English-like)\n')
    s = raw['solver']
    w('| population | mean | sd | 95%% interval |')
    w('|---|---|---|---|')
    for k, name in [('english_true_plaintext', 'genuine English, scored as-is'),
                    ('english_solved', 'genuine English, recovered by the solver'),
                    ('dorabella_shuffles', 'shuffles of Dorabella (noise floor)')]:
        d = s[k]
        w('| %s | %.4f | %.4f | [%.4f, %.4f] |' % (name, d['mean'], d['sd'], d['p2.5'], d['p97.5']))
    w('')
    w('| reading | best score | above %% of English | above %% of noise |')
    w('|---|---|---|---|')
    for r in s['readings']:
        w('| %s | %.4f | %.1f%% | %.1f%% |' % (
            r['label'], r['best_per_quadgram'], 100 * r['pct_english_below'],
            100 * r['pct_shuffles_below']))
    w('')
    w('Best-scoring plaintexts found (none of these is offered as a solution; they are '
      'shown because they illustrate how English-looking a maximum-fitness key can be '
      'at this length):\n')
    for r in s['readings']:
        w('- **%s** — `%s`' % (r['label'], r['best_plaintext']))
    w('')

    w('## 7. Solver power at n = 87\n')
    rec, dist, tp, do = pw['recovery'], pw['distributions'], pw['test_power'], pw['dorabella']
    w('%d genuine English texts of 87 characters were enciphered with a known random key '
      'and attacked with %d restarts each.\n' % (pw['n_controls'], pw['restarts']))
    w('| quantity | value |')
    w('|---|---|')
    w('| exact key recovered | %.1f%% |' % (100 * rec['exact_key_recovered']))
    w('| mean character accuracy of the recovered plaintext | %.1f%% |' % (100 * rec['char_accuracy_mean']))
    w('| median character accuracy | %.1f%% |' % (100 * rec['char_accuracy_median']))
    w('| runs recovering >90%% of characters | %.1f%% |' % (100 * rec['frac_accuracy_above_90pct']))
    w('| runs recovering <50%% of characters | %.1f%% |' % (100 * rec['frac_accuracy_below_50pct']))
    w('| runs where a **wrong** key outscored the true key | %.1f%% |' % (100 * rec['frac_best_beats_truth']))
    w('| mean score advantage of best key over true key | %+.4f |' % rec['mean_score_gap_best_minus_true'])
    w('')
    w('| quantity | value |')
    w('|---|---|')
    w('| noise floor (shuffles), 95th percentile | %.4f |' % dist['shuffle_best']['p95'])
    w('| power to detect genuine English at 5%% false-positive rate | %.1f%% |' % (100 * tp['power_at_5pct_fpr']))
    w('| Dorabella best score | %.4f |' % do['best_score'])
    w('| Dorabella p-value against the noise floor | %.3f |' % do['p_value_vs_shuffles'])
    w('| fraction of genuine English scoring below Dorabella | %.1f%% |' % (100 * do['pct_english_below']))
    w('')
    w('Dorabella best plaintext at %d restarts: `%s`\n' % (pw['restarts'], do['best_plaintext']))

    with open(OUT, 'w') as fh:
        fh.write('\n'.join(L) + '\n')
    print('wrote', OUT)


if __name__ == '__main__':
    main()
