(()=>{"use strict";
const deals=window.DEALS;
let di=0,progress=0,revealed=new Set(),selected=null,rating=1426,streak=4,soundOn=true,locked=false;
const $=id=>document.getElementById(id);const objects=[...document.querySelectorAll('.object')];
let audioCtx=null;function ensureAudio(){if(!audioCtx&&soundOn){try{audioCtx=new (window.AudioContext||window.webkitAudioContext)()}catch(e){}}}
function tone(freq=220,dur=.06,type='sine',gain=.035){if(!soundOn)return;ensureAudio();if(!audioCtx)return;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(gain,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+dur);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+dur)}
function clickSound(){tone(170,.045,'triangle',.03);setTimeout(()=>tone(260,.035,'triangle',.018),35)}function stampSound(){tone(95,.12,'square',.05)}
function vibrate(v){if(navigator.vibrate)navigator.vibrate(v)}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1100)}
function current(){return deals[di%deals.length]}
function render(){const d=current();progress=d.start;revealed=new Set();selected=null;locked=false;document.body.classList.remove('pressure2','pressure3');$('roomName').textContent='Deal #'+d.no;$('category').textContent=d.category;$('amount').textContent=d.amount;$('ask').innerHTML='Supplier asks <em>'+d.ask+'</em>';$('context').textContent=d.context;$('meta1').textContent=d.meta[0];$('meta2').textContent=d.meta[1];$('meta3').textContent=d.meta[2];$('rating').textContent=rating.toLocaleString();$('streak').textContent=streak;objects.forEach((o,i)=>{o.classList.remove('done','locked');o.querySelector('.costTag').textContent='+'+d.cards[i].cost+'%'});renderPositions();updateDial();$('showdown').classList.remove('open')}
function renderPositions(){const d=current();$('positions').innerHTML='';d.moves.forEach((m,i)=>{const b=document.createElement('button');b.className='position';b.innerHTML='<b>'+m[0]+'</b><small>'+m[1]+'</small>';b.addEventListener('click',()=>{selected=i;document.querySelectorAll('.position').forEach((x,j)=>x.classList.toggle('active',j===i));$('lockBtn').disabled=false;clickSound();vibrate(12)});$('positions').appendChild(b)});$('lockBtn').disabled=true}
function updateDial(){const deg=Math.round(progress*3.6);$('dialRing').style.background='conic-gradient(var(--red) '+deg+'deg,rgba(143,63,56,.08) '+deg+'deg)';$('needle').style.transform='translateX(-50%) rotate('+(-120+progress*2.4)+'deg)';$('pct').textContent=progress+'%';$('intelCount').textContent=revealed.size+'/6';let st='Discovery',pos='Flexible';if(progress>=75){st='Closing';pos='Weak';document.body.classList.add('pressure3')}else if(progress>=48){st='Positioning';pos='Narrowing';document.body.classList.add('pressure2')}else{document.body.classList.remove('pressure2','pressure3')}if(progress>=92){st='Final terms';pos='Very weak'}$('stage').textContent=st;$('positionState').textContent=pos;if(progress>=97)objects.filter((_,i)=>!revealed.has(i)).forEach(o=>o.classList.add('locked'))}
function inspect(i){if(locked||revealed.has(i)||progress>=97)return;const d=current(),c=d.cards[i];ensureAudio();progress=Math.min(100,progress+c.cost);revealed.add(i);objects[i].classList.add('done');updateDial();$('inspectCard').className='inspectCard '+c.skin;$('inspectType').textContent=c.type;$('inspectTitle').textContent=c.name;$('intelSignal').textContent=c.signal;$('intelDetail').textContent=c.detail;$('confidence').textContent=c.conf;$('paid').textContent='Cost +'+c.cost+'%';$('inspect').classList.add('open');clickSound();vibrate(18);toast('Deal advanced +'+c.cost+'%')}
function closeInspect(){$('inspect').classList.remove('open');tone(130,.04,'triangle',.02)}
objects.forEach((o,i)=>o.addEventListener('click',()=>inspect(i)));$('closeInspect').addEventListener('click',closeInspect);$('continueBtn').addEventListener('click',closeInspect);$('inspect').addEventListener('click',e=>{if(e.target===$('inspect'))closeInspect()});
$('makeMove').addEventListener('click',()=>{if(locked)return;$('decision').classList.add('open');ensureAudio();tone(120,.06,'triangle',.025);vibrate(14)});$('decisionClose').addEventListener('click',()=> $('decision').classList.remove('open'));$('decision').addEventListener('click',e=>{if(e.target===$('decision'))$('decision').classList.remove('open')});
$('lockBtn').addEventListener('click',()=>{if(selected===null)return;locked=true;$('decision').classList.remove('open');objects.forEach(o=>o.classList.add('locked'));revealShowdown()});
function revealShowdown(){const d=current(),hidden=[0,1,2,3,4,5].filter(i=>!revealed.has(i));let delay=120;hidden.forEach(i=>{setTimeout(()=>{objects[i].classList.remove('locked');objects[i].classList.add('done');clickSound()},delay);delay+=180});setTimeout(()=>{const m=d.moves[selected];const spent=progress-d.start;const timing=Math.max(36,Math.round(100-spent*.72));const efficiency=Math.max(38,Math.min(99,Math.round(96-Math.max(0,spent-36)*.75)));const value=Math.max(35,Math.min(99,m[2]+Math.min(3,revealed.size)));const risk=Math.max(35,Math.min(98,Math.round(60+(m[2]-58)*.53-Math.max(0,progress-77)*.28)));const score=Math.round(value*.41+risk*.18+efficiency*.23+timing*.18);const pct=Math.max(4,Math.min(98,Math.round(score*1.08-11)));$('outcome').textContent=m[3];$('valueCapture').textContent=d.value+' value captured';$('score').textContent=score;$('percentile').textContent=pct+'%';$('efficiency').textContent=efficiency;$('timing').textContent=timing;$('lesson').textContent=d.lesson;$('cmpYou').textContent=m[3];$('cmpAvg').textContent=d.avg;$('cmpTop').textContent=d.top;rating+=Math.round((score-70)*1.05);streak=score>=72?streak+1:0;$('showdown').classList.add('open');setTimeout(()=>{stampSound();vibrate([25,45,30])},950)},Math.max(700,delay+250))}
$('nextBtn').addEventListener('click',()=>{di=(di+1)%deals.length;$('showdown').classList.remove('open');setTimeout(render,160)});
$('sound').addEventListener('click',()=>{soundOn=!soundOn;$('sound').textContent=soundOn?'♪':'×';if(soundOn){ensureAudio();tone(220,.05,'triangle',.025)}});
const scene=$('scene');if(window.matchMedia('(pointer:fine)').matches){scene.addEventListener('pointermove',e=>{const r=scene.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;scene.style.transform='rotateX('+(-y*1.2)+'deg) rotateY('+(x*1.2)+'deg)'});scene.addEventListener('pointerleave',()=>scene.style.transform='rotateX(0deg) rotateY(0deg)')}
render();
})();
