window.DEALS=[
 {no:184,category:"Enterprise Software",amount:"$8.4M",ask:"+14%",context:"Renewal required before quarter end. The business says the platform is deeply embedded.",meta:["Renewal","Critical","38 days"],start:12,avg:"+0.8%",top:"−8.9%",value:"$1.65M",
  cards:[
   {name:"Market Report",type:"Market intelligence",cost:16,signal:"−8% → −14%",detail:"Comparable enterprise deals are landing well below your current commercial position.",conf:"High",skin:"paper",weight:13},
   {name:"Usage Analytics",type:"Internal data",cost:12,signal:"68% active",detail:"32% of purchased licences have not been active in the last 90 days.",conf:"High",skin:"dark",weight:15},
   {name:"Supplier Dossier",type:"Supplier intelligence",cost:18,signal:"FY END",detail:"The supplier closes its fiscal year in 12 days. Your account matters to the regional number.",conf:"Medium",skin:"folderView",weight:22},
   {name:"Alternative Bids",type:"Competitive intelligence",cost:25,signal:"6 months",detail:"Two credible competitors exist, but neither can complete migration inside six months.",conf:"High",skin:"paper",weight:19},
   {name:"Master Agreement",type:"Contract intelligence",cost:10,signal:"AUTO-RENEW",detail:"The notice window is approaching. Delay will materially weaken your alternatives.",conf:"High",skin:"paper",weight:16},
   {name:"Stakeholder Thread",type:"Internal intelligence",cost:14,signal:"LOCKED IN",detail:"The CIO has already ruled out migration this quarter. The supplier may suspect it.",conf:"Medium",skin:"dark",weight:15}],
  moves:[['Accept +3%','Defensive close',49,'+3.0%'],['Hold flat','Firm position',67,'0.0%'],['Push −8%','Aggressive',90,'−5.7%'],['3 years / −12%','Trade term for price',84,'−8.1%'],['Walk / Tender','Maximum pressure',52,'+2.4%']],
  lesson:"Supplier year-end pressure was real, but migration constraints limited the credible walk-away. The strongest play used pressure without pretending switching was immediate."},
 {no:185,category:"Consulting Services",amount:"$3.1M",ask:"+8%",context:"Phase two is beginning. The incumbent team holds knowledge the business does not want to lose.",meta:["Extension","Medium risk","21 days"],start:9,avg:"+1.9%",top:"−10.2%",value:"$422K",
  cards:[
   {name:"Market Report",type:"Rate benchmark",cost:15,signal:"−6% median",detail:"Comparable blended rate cards are around six percent below the incumbent's proposal.",conf:"Medium",skin:"paper",weight:14},
   {name:"Scope Analytics",type:"Demand intelligence",cost:14,signal:"−21% effort",detail:"Several workstreams taper next phase. The future requirement is materially smaller.",conf:"High",skin:"dark",weight:20},
   {name:"Supplier Dossier",type:"Supplier intelligence",cost:17,signal:"BENCH TIGHT",detail:"The incumbent's strongest team is becoming more heavily utilised across other clients.",conf:"Medium",skin:"folderView",weight:11},
   {name:"Alternative Bids",type:"Competitive intelligence",cost:24,signal:"2 credible",detail:"Two competitors can mobilise a suitable team within six weeks.",conf:"Medium",skin:"paper",weight:19},
   {name:"Master Agreement",type:"Contract intelligence",cost:11,signal:"NO MINIMUM",detail:"There is no minimum volume commitment. Scope can be reduced without a contractual penalty.",conf:"High",skin:"paper",weight:18},
   {name:"Stakeholder Thread",type:"Internal intelligence",cost:13,signal:"INCUMBENT BIAS",detail:"The sponsor has already told the incumbent that continuity is their preference.",conf:"High",skin:"dark",weight:18}],
  moves:[['Accept +2%','Preserve continuity',44,'+2.0%'],['Hold flat','Rate freeze',63,'0.0%'],['Push −10%','Reprice aggressively',83,'−7.4%'],['Cut scope / −6%','Demand + price',94,'−13.6%'],['Rebid','Full competition',76,'−8.3%']],
  lesson:"The biggest lever was not the rate card. It was lower future demand combined with a contract carrying no minimum commitment."},
 {no:186,category:"Logistics",amount:"$12.7M",ask:"+11%",context:"The primary carrier cites capacity constraints and fuel pressure. Service has been strong for eighteen months.",meta:["Lane renewal","High service risk","45 days"],start:11,avg:"+4.1%",top:"−3.8%",value:"$1.02M",
  cards:[
   {name:"Market Report",type:"Market intelligence",cost:19,signal:"+7% market",detail:"Lane pricing has genuinely moved up. The supplier's market story is not fabricated.",conf:"High",skin:"paper",weight:20},
   {name:"Volume Analytics",type:"Demand intelligence",cost:12,signal:"−9% forecast",detail:"Next-year shipment volume is forecast lower, especially on two of the most expensive lanes.",conf:"Medium",skin:"dark",weight:15},
   {name:"Supplier Dossier",type:"Supplier intelligence",cost:15,signal:"CAPACITY TIGHT",detail:"Fleet utilisation supports part of the supplier's capacity claim. They do have constraints.",conf:"Medium",skin:"folderView",weight:13},
   {name:"Alternative Bids",type:"Competitive intelligence",cost:28,signal:"LIMITED",detail:"Backup carriers are already close to peak utilisation on the critical lanes.",conf:"High",skin:"paper",weight:22},
   {name:"Master Agreement",type:"Contract intelligence",cost:10,signal:"FUEL INDEX",detail:"Fuel is already separately indexed. It should not also inflate the base rate.",conf:"High",skin:"paper",weight:18},
   {name:"Operations Thread",type:"Internal intelligence",cost:14,signal:"ZERO TOLERANCE",detail:"A service failure would stop production within 48 hours. Reliability is worth real money here.",conf:"High",skin:"dark",weight:12}],
  moves:[['Accept +8%','Secure capacity',80,'+8.0%'],['Hold flat','Hard freeze',58,'+5.2%'],['Push −5%','Aggressive',39,'+9.7%'],['2 years / +3%','Trade term for capacity',93,'+3.0%'],['Rebid','Open market',46,'+11.8%']],
  lesson:"The supplier had real leverage. The hidden opportunity was separating fuel from base-rate inflation and trading term for capacity instead of forcing an unrealistic headline reduction."},
 {no:187,category:"Cloud Infrastructure",amount:"$19.6M",ask:"+6%",context:"Consumption is climbing rapidly. Engineering wants flexibility; Finance wants a stronger commitment discount.",meta:["Consumption commit","Strategic","31 days"],start:10,avg:"−1.1%",top:"−12.4%",value:"$2.37M",
  cards:[
   {name:"Market Report",type:"Market intelligence",cost:17,signal:"DISCOUNTS ↑",detail:"Comparable enterprise commits are receiving deeper discounts as providers defend strategic share.",conf:"Medium",skin:"paper",weight:16},
   {name:"Usage Analytics",type:"Demand intelligence",cost:13,signal:"+38% growth",detail:"Consumption is rising much faster than forecast, but the shape of that growth is uneven.",conf:"High",skin:"dark",weight:17},
   {name:"Supplier Dossier",type:"Supplier intelligence",cost:16,signal:"SHARE AT RISK",detail:"The provider is protecting marquee accounts from multi-cloud erosion this quarter.",conf:"Medium",skin:"folderView",weight:19},
   {name:"Alternative Bids",type:"Competitive intelligence",cost:27,signal:"MULTI-CLOUD",detail:"A credible alternative exists, but engineering duplication would erode part of the savings.",conf:"Medium",skin:"paper",weight:12},
   {name:"Master Agreement",type:"Contract intelligence",cost:10,signal:"FLEX ±15%",detail:"The commitment band can flex fifteen percent without penalty, materially reducing volume risk.",conf:"High",skin:"paper",weight:22},
   {name:"Engineering Thread",type:"Internal intelligence",cost:13,signal:"VOLATILE",detail:"Roadmap changes could shift workload mix even if total cloud consumption keeps rising.",conf:"Medium",skin:"dark",weight:14}],
  moves:[['Accept +2%','Keep flexibility',51,'+2.0%'],['Hold flat','No new commitment',66,'0.0%'],['Push −10%','Price pressure',79,'−7.8%'],['3 years / −14%','Commit strategically',94,'−12.1%'],['Multi-cloud','Diversify',61,'−3.3%']],
  lesson:"The flex band made commitment much safer than it first appeared. The best play found contract structure before treating the decision as a pure price negotiation."},
 {no:188,category:"Marketing Agency",amount:"$5.7M",ask:"+5%",context:"The agency says senior talent costs are rising. Brand leadership wants continuity through a major launch.",meta:["Agency renewal","Launch critical","27 days"],start:8,avg:"+0.6%",top:"−9.7%",value:"$631K",
  cards:[
   {name:"Market Report",type:"Fee benchmark",cost:16,signal:"+2% market",detail:"Senior strategy rates have risen, but production and junior layers remain flat to down.",conf:"Medium",skin:"paper",weight:14},
   {name:"Scope Analytics",type:"Demand intelligence",cost:13,signal:"PYRAMID HEAVY",detail:"The proposed staffing mix contains significantly more senior hours than recent actual delivery.",conf:"High",skin:"dark",weight:21},
   {name:"Supplier Dossier",type:"Supplier intelligence",cost:18,signal:"NEW BIZ LOSS",detail:"The agency recently lost a major client and has utilisation pressure in two offices.",conf:"Medium",skin:"folderView",weight:18},
   {name:"Alternative Bids",type:"Competitive intelligence",cost:25,signal:"3 challengers",detail:"Three agencies can cover the work, but only one has launch-ready creative capacity.",conf:"Medium",skin:"paper",weight:17},
   {name:"Master Agreement",type:"Contract intelligence",cost:9,signal:"OPEN BOOK",detail:"The agreement grants audit rights over pass-through production and third-party markups.",conf:"High",skin:"paper",weight:17},
   {name:"Brand Thread",type:"Internal intelligence",cost:14,signal:"CONTINUITY",detail:"Brand leadership will tolerate commercial pressure, but not a full agency change before launch.",conf:"High",skin:"dark",weight:13}],
  moves:[['Accept +3%','Continuity first',54,'+3.0%'],['Hold flat','Fee freeze',69,'0.0%'],['Push −8%','Hard reprice',77,'−5.1%'],['Rebuild pyramid / −6%','Mix + rate',95,'−11.1%'],['Full rebid','Change agency',55,'−1.8%']],
  lesson:"The value was hidden in the staffing pyramid, not the headline rate. Strong players protected continuity while removing unnecessary senior-layer cost."}
];
